version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:delegated
volumes:
  database_data:
    driver: local
