AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  platform-exercise
  
  Fender platform-exercise for Allison Hanna interview January 2021

Globals:
  Function:
    Timeout: 5
Parameters:
  POSTGRES_URL:
    Default: "Postgres url not set"
    Description: "Postgres url"
    Type: String

Resources:
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-user/
      Handler: create-user
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /user
            Method: POST
      Environment:
        Variables:
          postgresURL: !Ref POSTGRES_URL
  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update-user/
      Handler: update-user
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /user
            Method: PATCH
      Environment:
        Variables:
          postgresURL: !Ref POSTGRES_URL
  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete-user/
      Handler: delete-user
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /user
            Method: DELETE
      Environment:
        Variables:
          postgresURL: !Ref POSTGRES_URL
  ValidateEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: validate-email/
      Handler: validate-email
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /validate-email
            Method: POST
      Environment:
        Variables:
          PARAM1: VALUE
  CheckPasswordStrengthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: password-strength/
      Handler: password-strength
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /password-strength
            Method: POST
      Environment:
        Variables:
          PARAM1: VALUE

Outputs:
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
